twig:
    globals:
        icons:
            create: 'fa-regular fa-square-plus'
            modify: 'fa-regular fa-pen-to-square'
            delete: 'fa-regular fa-trash'
            save: 'fa-regular fa-save'
            disable: 'fa-solid fa-ban'
        label:
            create: 'btn.create'
            modify: 'btn.modify'
            delete: 'btn.delete'
            save: 'btn.save'
            disable: 'btn.disable'